alias ls='ls --color=auto --group-directories-first' 
alias ll='ls -la --color=auto --group-directories-first'
alias cls='clear && ls'
alias cll='clear && ll'
alias grep='grep --color=auto'
alias scim='sc-im'
alias photo='sxiv'
alias size='du -ah --max-depth=1'
alias youtube-dl='youtube-dl --add-metadata'
alias youtube-dl720="youtube-dl -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'"
